[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"

[monorepo]
root = "./backend"

[[services]]
name = "web"
httpPort = 5000

[build.environment]
NODE_VERSION = "18"
